### ISSUE TITLE
[Feature Request] MySQL data score

### ISSUE THREAD

**Issue by Yukyxy** [ShaneBeeTK/HungerGames#1]
Hello could you add mysql support for score ? please

**Comment by ShaneBeee** [comment]
> Hello could you add mysql support for score ? please

There is no score in this thing

**Comment by ShaneBeee** [comment]
A recommendation of something you can do:
You can have the game run commands when a player wins. You can use this to a run a command for possibly another plugin that has scoring.

**Comment by ShaneBeee** [comment]
Im closing this as its been 8 days and I haven't received any more info on what exactly you are looking for here.
