### ISSUE TITLE
[BUG] The main scoreboard is not restored after a game

### ISSUE THREAD

**Issue by Jocke155** [ShaneBeeTK/HungerGames#10]
**Description**
When I have played in an arena and leave, I have to re-log for the main scoreboard to be displayed again. 

**To Reproduce**
Have a main scoreboard, and join and leave an arena.

**Expected behavior**
The main scoreboard should be restored when the game is completed

**Comment by ShaneBeee** [comment]
I figured this was going to happen.
Gonna do some research and try fix it!

**Comment by ShaneBeee** [comment]
Fixed
Will appear in next update
