### ISSUE TITLE
[Feature Request] Moving world border in arenas

### ISSUE THREAD

**Issue by Jocke155** [ShaneBeeTK/HungerGames#11]
**The idea**
Add an option to have a moving worldborder in some arenas. Once the time goes down, the border comes closer and closer to the middle.

**Comment by ShaneBeee** [comment]
**1)** Im not entirely sure how I feel about this. It would require sending packets to the player to simulate a world border for each player. Me personally, I wouldn't use this feature, but the plugin isn't just about me, so I will add the enhancement label, and think about this a bit more.

**2)** This is a bit out of my comfort zone for handling due to the packets. I've never worked with packets before.

**Comment by Jocke155** [comment]
You don't need to use packets, there is a WorldBorder interface in Spigot.
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/WorldBorder.html

**Comment by ShaneBeee** [comment]
Yes, but that is for the entire world and would affect **all** players in a world, not just the ones in an arena

**Comment by Jocke155** [comment]
Yeah that's true, but that's why you can add it as an option, in case that each arena is separated by a world.

**Comment by ShaneBeee** [comment]
> Yeah that's true, but that's why you can add it as an option, in case that each arena is separated by a world.

I wouldn't do something like that. Theres a very good chance that people are using arenas in world occupied by other players, or multiple arenas in one world. 
Adding an option using the Bukkit methods you have shown above, would make this option **ONLY** available for servers creating arenas in a new world only occupied by the arena, and kind of takes away from the purpose of this plugin.

If this feature were to be added, the only way to properly implement it that could work for every server type, would be packets.

**Comment by Jocke155** [comment]
Okay, if you were to use packets have a look at WorldBorderAPI by yannicklamprecht. He provides some very useful methods you could try to implement :)
https://github.com/yannicklamprecht/WorldBorderAPI

**Comment by ShaneBeee** [comment]
This repo is now being closed and moved to [**BitBucket**](https://bitbucket.org/ShaneBeeStudios/hungergames/)
