### ISSUE TITLE
[BUG] Kill bug

### ISSUE THREAD

**Issue by pterrmeister** [ShaneBeeTK/HungerGames#12]
**Describe the bug**
The bug is something to do with killing players.
**To Reproduce**
This bug occurs everytime you kill a player in hunger games where the kill won't register which means the game still displays and recognizes three players alive (Lets say 3 players as the total players in the game). 

**Expected behavior**
The outcome of such bug produces a problem in ending the games in such case the last player alive is still in the arena waiting for the time limit to end the game.

**Screenshots**
All i have is the error message in the server console: (Sorry if it might spam)
(Error start from the bottom to the top):
org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[Spigot.jar:git-Spigot-3cb9dcb-8b1588e]
14.04 09:47:14 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_202]
14.04 09:47:14 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202]
14.04 09:47:14 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202]
14.04 09:47:14 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
14.04 09:47:14 [Server] INFO at me.minebuilders.hg.listeners.GameListener.onDeath(GameListener.java:89) ~[?:?]
14.04 09:47:14 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.event.entity.PlayerDeathEvent.setCancelled(Z)V
14.04 09:47:14 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
14.04 09:47:14 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [Spigot.jar:git-Spigot-3cb9dcb-8b1588e]
14.04 09:47:14 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [Spigot.jar:git-Spigot-3cb9dcb-8b1588e]
14.04 09:47:14 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [Spigot.jar:git-Spigot-3cb9dcb-8b1588e]
14.04 09:47:14 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [Spigot.jar:git-Spigot-3cb9dcb-8b1588e]
14.04 09:47:14 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [Spigot.jar:git-Spigot-3cb9dcb-8b1588e]
14.04 09:47:14 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_202]
14.04 09:47:14 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_202]
14.04 09:47:14 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[Spigot.jar:git-Spigot-3cb9dcb-8b1588e]
14.04 09:47:14 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:13) ~[Spigot.jar:git-Spigot-3cb9dcb-8b1588e]
14.04 09:47:14 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:69) ~[Spigot.jar:git-Spigot-3cb9dcb-8b1588e]
14.04 09:47:14 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1856) ~[Spigot.jar:git-Spigot-3cb9dcb-8b1588e]
14.04 09:47:14 [Server] INFO at net.minecraft.server.v1_13_R2.EntityPlayer.attack(EntityPlayer.java:1343) ~[Spigot.jar:git-Spigot-3cb9dcb-8b1588e]
14.04 09:47:14 [Server] INFO at net.minecraft.server.v1_13_R2.EntityHuman.attack(EntityHuman.java:1044) ~[Spigot.jar:git-Spigot-3cb9dcb-8b1588e]
14.04 09:47:14 [Server] INFO at net.minecraft.server.v1_13_R2.EntityPlayer.damageEntity(EntityPlayer.java:625) ~[Spigot.jar:git-Spigot-3cb9dcb-8b1588e]
14.04 09:47:14 [Server] INFO at net.minecraft.server.v1_13_R2.EntityHuman.damageEntity(EntityHuman.java:792) ~[Spigot.jar:git-Spigot-3cb9dcb-8b1588e]
14.04 09:47:14 [Server] INFO at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:1055) ~[Spigot.jar:git-Spigot-3cb9dcb-8b1588e]
14.04 09:47:14 [Server] INFO at net.minecraft.server.v1_13_R2.EntityPlayer.die(EntityPlayer.java:491) ~[Spigot.jar:git-Spigot-3cb9dcb-8b1588e]
14.04 09:47:14 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:591) ~[Spigot.jar:git-Spigot-3cb9dcb-8b1588e]
14.04 09:47:14 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) ~[Spigot.jar:git-Spigot-3cb9dcb-8b1588e]
14.04 09:47:14 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) ~[Spigot.jar:git-Spigot-3cb9dcb-8b1588e]
14.04 09:47:14 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-3cb9dcb-8b1588e]
14.04 09:47:14 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[Spigot.jar:git-Spigot-3cb9dcb-8b1588e]
14.04 09:47:14 [Server] INFO org.bukkit.event.EventException: null
14.04 09:47:14 [Server] ERROR Could not pass event PlayerDeathEvent to HungerGames v4.1.0
1

**Environment Information (please complete the following information):**
 - Spigot 1.13.2
 - The Latest updated version of HungerGames

**Additional context**
To be honest, i feel like the root cause of this bug is a plugin that is interfering your plugin specifically in term of Killing Players. All i can list of plugins that i currently use in the server which may the reason to cause such problem are:
KillerMoney
McMMo
CombatLog
Factions

**Comment by ShaneBeee** [comment]
First of all, any dev will tell you, they quite dislike hearing this:
""The Latest updated version of HungerGames""

Here is why:
"" ERROR Could not pass event PlayerDeathEvent to HungerGames v4.1.0""

![](https://i.imgur.com/tDQ4qrI.png)

4.1.0 is **not** the latest version.
This error was fixed in version 4.1.1

**Comment by pterrmeister** [comment]
Ohh sorry about that, Thanks for respoding
