### ISSUE TITLE
[BUG] Trackstick works on players in spectator mode

### ISSUE THREAD

**Issue by Jocke155** [ShaneBeeTK/HungerGames#13]
**Description**
When admins or players with spectator mode in the arenas are present, the track stick tracks them.

**To Reproduce**
Be present in spectator mode near a player, and a player in the arena should use the tracking stick.

**Expected behavior**
Only track players who are actually in the arena and not players in gamemodes that are not survival.

**Comment by ShaneBeee** [comment]
Thank you for letting me know, Ill make sure to update it to only check for players that are actually in the game.
