### ISSUE TITLE
[Feature Request] button leave

### ISSUE THREAD

**Issue by Yukyxy** [ShaneBeeTK/HungerGames#3]
Hello,
when players wait on the map it should have a button "leave" slot 9.

**Comment by ShaneBeee** [comment]
Im 50/50 on this.
I do like the concept but I don't really care for the idea of taking up an inventory slot.

I could always implement this, and have it configurable (default to off) and this way a server owner can choose whether or not they want this in their game.

**Comment by ShaneBeee** [comment]
Okay so I have thought about this more and more.
In my honest opinion, this makes absolutely zero sense.
To leave a game a player just has to simply type `/hg leave` or they can type `/hg l` and hit tab.
I really dont see the point in taking up a hotbar space for this. I don't feel like it brings anything to the game, it wouldnt really serve any purpose.

So Im sorry but Im closing this, as it just doesn't seem like anything that fits this game.
