### ISSUE TITLE
[Feature Request] gui kit + Price 

### ISSUE THREAD

**Issue by Yukyxy** [ShaneBeeTK/HungerGames#4]
Hello Could you add a GUI for the kits? (instead of commands) and price for kit? that the player can buy kits with his money. please

**Comment by ShaneBeee** [comment]
Hey
I like the idea of the price. That would be a good add for sure.
As for the gui, I dont really think its all that necessary, but its possibly something I could add.
Ill put it on my list

**Comment by ShaneBeee** [comment]
This repo is now being closed and moved to [**BitBucket**](https://bitbucket.org/ShaneBeeStudios/hungergames/)
