### ISSUE TITLE
[BUG] Not teleported out after staying in respawn screen

### ISSUE THREAD

**Issue by Jocke155** [ShaneBeeTK/HungerGames#6]
**Describe the bug**
When I kill a player in a game, they are not teleported out if they stay in the respawn screen.

**To Reproduce**
Kill a player in an active game, and don't click respawn.

**Expected behavior**
player.spigot().respawn(); , then teleport. Else the client will display the respawn screen, and cannot be teleported out.

**Environment Information**
CraftBukkit version git-Spigot-e6eb36f-d3ed151 (MC: 1.13.2)
Hungergames 4.0.0

**Comment by ShaneBeee** [comment]
This shouldn't be happening.
Every time I have ever died, I've never got the "Death screen" I always just respawn right back at the lobby.
I will need to do more testing.

**Comment by ShaneBeee** [comment]
I just realized.... what is the max health set to on your server?
I can't replicate this.

When I changed it to what you have in the PR.... it works BUT theres a bit of "lag" after the player dies and spawns back at the lobby.

**Comment by Jocke155** [comment]
I got the teleporting to work now, (it was a problem with another plugin) but the respawn screen is still visible after the revive, even though I can see my full health behind the respawn menu. The server seem to think that I am alive and I can be killed by other players in the lobby, but the client think that I still have to press respawn so this is really weird. Pressing respawn only closes the respawn menu, it does not teleport me anywhere.

Worth to mention that the lobby and the arena is not in the same world.

**Comment by ShaneBeee** [comment]
Hey good to know.

Okay, so i tried with the respawn thing, and it was horrid... BUT i tried with both and it was totally fine, so Im thinking that MIGHT be the fix

**Comment by ShaneBeee** [comment]
Okay I think this is fixed.
Im doubling up the methods so it'll repair health first, then if that doesn't work it'll respawn you.

This will appear in the next update

**Comment by ShaneBeee** [comment]
I posted a small bug fix beta update.
I dont like to do multiple updates a week so this will not appear on SpigotMC.
I will plan a bigger update for the weekend with more updates and changes I do during the week.
You can grab the beta release [**HERE**](https://github.com/ShaneBeeTK/HungerGames/releases/tag/4.0.1-Beta1)
