### ISSUE TITLE
[Feature Request] Minimum game length required for reward

### ISSUE THREAD

**Issue by Jocke155** [ShaneBeeTK/HungerGames#9]
**The problem**
The problem is that players can use the HG arena to farm rewards, by just going to their friend and die within 30 seconds after the game has started.

**Describe the solution you'd like**
A value for the minimum required time a game needs to be in order for the winner(s) to get a reward. This ensure that the game is legitimate, or at least it would take a lot longer to farm these rewards since the players must be in the arena for a while.

I think that the minimum time could either be in seconds, or a percentage of the full game time.

**Comment by ShaneBeee** [comment]
Im glad you brought this up. Ive had a plan for a while now to revamp the system.

They dont even need to kill each other. 2 players can join, stand there and wait for the time to run out, hell I think one can just run /hg leave, and the other is classified as a winner.
I definitely need to work in a crap ton of conditions to make sure the winner actually has to do something to win.

**Comment by ShaneBeee** [comment]
Im also labelling this as a bug, as it is kind of a bug as well.

**Comment by ShaneBeee** [comment]
One suggestion I do have is setting the min players higher. For example something like 5.

Im trying to think of different ways to prevent players from farming rewards. I know that has always been an issue with this plugin. 
Back when I used it on a server a year or two ago, I created a system where player's had to **pay** to get INTO the arena, which at the end of the day, prevented them from farming the rewards.

**Comment by Jocke155** [comment]
My server is pretty low-pop, so I set the min players to 3.
I cloned Hungergames and just made a new config value called "minimum-game-length: 180" in the reward section, which means if they actually farm rewards, they at least have to be in the game for amount of time.

**Comment by ShaneBeee** [comment]
I have a few ideas in mind to help kill this.

1) One of the issues with the plugin, is if you stop the game in any manner, the current players in the game "win" so I want to nip that in bud. Im going to create a system where there needs to be a death for a player to actually win a reward. Any other stopping of the game will not pay out.

2) I was thinking of doing a "money pot" for the win. 
ex: You set the price a player pays to enter the game, lets say $200 for this example. So if 5 players join, the pot is at $1000, the winner gets a thousand.
In your case, if 2 players join, the pot is at $400, so even if your players DO try to farm, they are gaining nothing really.

What's your thoughts on charging players to enter the arenas?

**Comment by Jocke155** [comment]
I'm not sure about charging players, since they just might want to go in the arena to have some fun, but should still get rewarded when someone win. Having to pay will remove a part of that fun.

I have another idea though, have a list of recent players in an arena. If the same players join again shortly afterwards, the reward is scaled down to prevent farming.

**Comment by ShaneBeee** [comment]
> I'm not sure about charging players, since they just might want to go in the arena to have some fun, but should still get rewarded when someone win. Having to pay will remove a part of that fun.

Fair enough, If I do add that, Ill add it as an option. 


> I have another idea though, have a list of recent players in an arena. If the same players join again shortly afterwards, the reward is scaled down to prevent farming.

This might be a bit difficult to do, having to create another list to house players. Ill keep brainstorming and see what I come up with.
Im currently working on a system, so the only time a player "wins" and gets paid, is if they are truly the last man standing (ie: if 2 players are in the arena, and one does `/hg leave` the other will not be classified as a winner, they will need to have killed them)

**Comment by ShaneBeee** [comment]
[**BitBucket**](https://bitbucket.org/ShaneBeeStudios/hungergames/)
